<?php

use function Livewire\Volt\{title};

title('Raumverwaltung');

?>

<x-intranet-app-raumverwaltung::raumverwaltung-layout heading="Raumverwaltung" subheading="Verwaltung von Räumen und Standorten">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-raumverwaltung::raumverwaltung-layout>